/* Meaningful behavior/real inference QA. Development-only dependency: playwright. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),screens=path.join(root,'docs/screenshots');fs.mkdirSync(screens,{recursive:true});
let server,browser,backend;
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.wasm':'application/wasm'};
(async()=>{
 server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end()}res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp'});fs.createReadStream(p).pipe(res)}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port+'/';
 browser=await chromium.launch({executablePath:process.env.HOLO_CHROME_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1512,height:1120},locale:'zh-TW'}),page=await context.newPage(),errors=[],external=[];
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(url)&&!r.url().startsWith('http://127.0.0.1:8766/'))external.push(r.url())});
 await page.goto(url);await page.waitForFunction(()=>window.HoloMuseum);await page.waitForFunction(()=>document.getElementById('originalImage').naturalWidth>0);await page.click('#pauseVisitors');
 const snapshot=()=>page.evaluate(()=>HoloMuseum.snapshot());let s=await snapshot();assert.equal(s.artworkCount,100);const first=s.selectedId;
 await page.keyboard.press('r');assert.notEqual((await snapshot()).selectedId,first);await page.keyboard.press('l');assert.equal((await snapshot()).selectedId,first);
 await page.click('#nextVisitor');assert.notEqual((await snapshot()).selectedId,first);await page.click('#prevVisitor');assert.equal((await snapshot()).selectedId,first);
 for(const e of ['joy','anger','sadness','delight']){await page.click(`[data-emotion="${e}"]`);assert.equal((await snapshot()).emotion,e)}
 await page.fill('#utterance','L R WASD 喜怒哀樂');await page.keyboard.type('lrwasd');assert.equal((await snapshot()).selectedId,first);assert.match(await page.inputValue('#utterance'),/lrwasd$/);
 await page.locator('h1').click();const before=await snapshot();await page.keyboard.down('ArrowRight');await page.keyboard.down('w');await page.waitForTimeout(450);await page.keyboard.up('ArrowRight');await page.keyboard.up('w');s=await snapshot();assert.ok(s.x>before.x+.25);assert.ok(s.gaze.y<before.gaze.y-.1);
 await page.evaluate(()=>HoloMuseum.move(4));assert.equal((await snapshot()).artworkIndex,1);await page.click('#cameraFirst');assert.equal((await snapshot()).camera,'first');await page.waitForTimeout(100);const nearView=await page.locator('#museumCanvas').evaluate(c=>c.toDataURL());await page.evaluate(()=>HoloMuseum.move(0,1));await page.waitForTimeout(100);assert.notEqual(await page.locator('#museumCanvas').evaluate(c=>c.toDataURL()),nearView);await page.click('#cameraThird');assert.equal((await snapshot()).camera,'third');
 await page.evaluate(()=>{HoloMuseum.selectArtwork(0);for(let i=1;i<100;i++)HoloMuseum.move(4)});assert.equal((await snapshot()).artworkIndex,99);await page.evaluate(()=>HoloMuseum.move(-4));assert.equal((await snapshot()).artworkIndex,98);await page.evaluate(()=>HoloMuseum.selectArtwork(0));
 await page.click('#openCollection');assert.equal(await page.locator('.collection-item').count(),100);await page.fill('#collectionSearch','Mona Lisa');assert.equal(await page.locator('.collection-item').count(),1);await page.click('.collection-item');assert.equal((await snapshot()).artworkIndex,0);
 const languages=[];for(const lang of ['en','ja','ko','es','zh-TW']){await page.selectOption('#language',lang);languages.push({lang,title:await page.locator('h1').innerText()})}assert.equal(new Set(languages.map(x=>x.title)).size,5);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.fill('#utterance','妳為什麼微笑？我今天很難過。');await page.click('[data-emotion="sadness"]');await page.evaluate(()=>HoloMuseum.setGaze({x:.445,y:.313}));await page.click('#sendMessage');assert.equal((await snapshot()).response.source,'rehearsal');await page.screenshot({path:path.join(screens,'desktop-rehearsal.png'),fullPage:true});
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,locale:'ja-JP'}),mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);await mobile.waitForFunction(()=>window.HoloMuseum);assert.equal(await mobile.evaluate(()=>document.documentElement.lang),'ja');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 const mobileFirst=await mobile.evaluate(()=>HoloMuseum.snapshot().selectedId);await mobile.tap('#nextVisitor');assert.notEqual(await mobile.evaluate(()=>HoloMuseum.snapshot().selectedId),mobileFirst);await mobile.tap('#prevVisitor');assert.equal(await mobile.evaluate(()=>HoloMuseum.snapshot().selectedId),mobileFirst);await mobile.tap('[data-emotion="anger"]');assert.equal(await mobile.evaluate(()=>HoloMuseum.snapshot().emotion),'anger');
 await mobile.fill('#utterance','あなたの微笑みは何を伝えていますか？');await mobile.tap('#sendMessage');assert.ok(await mobile.locator('#portraitReply').innerText());
 await mobile.locator('#gazePad').scrollIntoViewIfNeeded();const l=await mobile.locator('[data-action="gaze-up"]').boundingBox(),r=await mobile.locator('[data-action="walk-right"]').boundingBox();assert.ok(l.y>=0&&r.y>=0&&l.y+l.height<=844&&r.y+r.height<=844,'Both touch pads must fit together');const mb=await mobile.evaluate(()=>HoloMuseum.snapshot()),cdp=await mobileContext.newCDPSession(mobile);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:l.x+l.width/2,y:l.y+l.height/2,id:1},{x:r.x+r.width/2,y:r.y+r.height/2,id:2}]});await mobile.waitForTimeout(600);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const ma=await mobile.evaluate(()=>HoloMuseum.snapshot());assert.ok(ma.x>mb.x+.3);assert.ok(ma.gaze.y<mb.gaze.y-.15);await mobile.screenshot({path:path.join(screens,'mobile.png'),fullPage:true});
 let generation=null;if(process.env.HOLO_TEST_REAL==='1'){
  backend=spawn('python3',[path.join(root,'optional-image-engine/server.py'),'--preload'],{cwd:root,env:{...process.env,PYTHONPATH:process.env.HOLO_PYTHON_DEPS||''},stdio:['ignore','pipe','pipe']});let blog='';backend.stdout.on('data',d=>blog+=d);backend.stderr.on('data',d=>blog+=d);
  for(let i=0;i<60;i++){try{const h=await fetch('http://127.0.0.1:8766/health');if(h.ok)break}catch{}await new Promise(r=>setTimeout(r,250));if(i===59)throw Error('Neural engine unavailable: '+blog)}
  await page.locator('details.neural-settings summary').click().catch(()=>{});await page.locator('#connectNeural').click();await page.waitForFunction(()=>HoloMuseum.state.neuralConnected);
  await page.click('#loadModel');await page.waitForFunction(()=>HoloMuseum.state.modelReady,{},{timeout:180000});await page.fill('#utterance','妳的微笑為什麼讓人平靜？');await page.click('#sendMessage');await page.waitForFunction(()=>!HoloMuseum.state.generating,{},{timeout:240000});generation=(await snapshot()).response;assert.equal(generation.source,'local-llm');assert.notEqual(generation.text,generation.input.utterance);assert.ok(generation.neuralImage?.startsWith('data:image/png;base64,'));assert.equal(await page.locator('#neuralPortrait').isVisible(),true);assert.ok(await page.locator('#neuralPortrait').evaluate(e=>e.naturalWidth>0));
  await page.screenshot({path:path.join(screens,'desktop-neural.png'),fullPage:true});await page.locator('.portrait-stage').screenshot({path:path.join(root,'../output/HoloArtisan_PortraitMuseum_Preview.png')});delete generation.neuralImage;generation.info=await page.evaluate(()=>HoloGenerator.info());
 }
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);const report={testedAt:new Date().toISOString(),browser:browser.version(),passed:true,errors,external,languages,artworks:100,controls:['L/R keyboard and touch viewer switching','4 emotions','input does not steal keys','keyboard independent gaze+walk','walk through all100 artworks','first/third view','collection search','mobile simultaneous touch pads','per-viewer response state'],generation,mobile:{width:390,height:844,locale:'ja',multiTouch:true},limitations:'Linux Chromium and mobile emulation; no physical mobile/Windows/macOS/Safari devices.'};fs.writeFileSync(path.join(__dirname,'museum-integration-result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close();if(backend)backend.kill()});
