const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');let server,browser;
(async()=>{
 const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.wasm':'application/wasm','.jpg':'image/jpeg','.woff':'font/woff','.svg':'image/svg+xml'};
 server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]),p=path.resolve(root,'.'+(u==='/'?'/index.html':u));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end()}res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream'});fs.createReadStream(p).pipe(res)}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url=`http://127.0.0.1:${server.address().port}/`;
 browser=await chromium.launch({executablePath:process.env.HOLO_CHROME_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1200,height:900},locale:'zh-TW'}),page=await context.newPage();await page.goto(url);await page.waitForFunction(()=>window.HoloMuseum);await page.click('#saveOffline');await page.waitForFunction(()=>/離線資料已備妥/.test(document.getElementById('offlineStatus').textContent),{},{timeout:240000});console.log('Full offline cache complete');await page.close();await context.setOffline(true);
 const offline=await context.newPage(),errors=[];offline.on('pageerror',e=>errors.push(e.message));await offline.goto(url+'?lang=en');await offline.waitForFunction(()=>window.HoloMuseum);await offline.waitForFunction(()=>document.getElementById('originalImage').naturalWidth>0);await offline.evaluate(()=>HoloMuseum.selectArtwork(99));await offline.waitForFunction(()=>document.getElementById('originalImage').naturalWidth>0);const last=await offline.evaluate(()=>HoloMuseum.snapshot().artworkId);await offline.evaluate(()=>HoloMuseum.selectArtwork(0));await offline.click('#loadModel');await offline.waitForFunction(()=>HoloMuseum.state.modelReady,{},{timeout:180000});await offline.fill('#utterance','What does your smile tell me?');await offline.click('#sendMessage');await offline.waitForFunction(()=>!HoloMuseum.state.generating,{},{timeout:180000});const result=await offline.evaluate(()=>({reply:HoloMuseum.snapshot().response,info:HoloGenerator.info()}));assert.equal(result.reply.source,'local-llm');assert.ok(result.reply.text.length>3);assert.notEqual(result.reply.text,'What does your smile tell me?');assert.deepEqual(errors,[]);
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'offline-manifest.json'))),report={passed:true,testedAt:new Date().toISOString(),browser:browser.version(),network:'Playwright context.setOffline(true) before new page navigation and inference',cacheBytes:manifest.bytes,cacheFiles:manifest.files.length,lastArtworkLoaded:last,model:result.info,reply:result.reply.text,elapsedMs:result.reply.elapsedMs,pageErrors:errors,limitations:'Desktop Chromium cache and offline emulation; physical phone storage eviction and mobile browser quotas not verified.'};fs.writeFileSync(path.join(__dirname,'offline-cache-result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close()});
